// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apkkklwenihriulmjtzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwa2trbHdlbmlocml1bG1qdHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTY5NTAsImV4cCI6MjA2MDM3Mjk1MH0.YLx6p3FWNX5k9KoMG-II0Ie0Y6jJJ8uMhJP667uq6ig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);