// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mykwlllrecqrdeosbkrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15a3dsbGxyZWNxcmRlb3Nia3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MTYyNjEsImV4cCI6MjA5NjQ5MjI2MX0.2jHVkYR7GmzhPjUvrhUqXvIkGVNjgqjaG5vx81Y9XzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});